### ISSUE TITLE
Better explanation/example of room listeners

### ISSUE THREAD

**Issue by gregmax17** [colyseus/colyseus.js#12]
Just like the topic says, can you please provide some more examples and/or better explanation on how these room listeners work?

According to your example, the `entities` property for your state is assumed to be an array, correct? From my experience when the user is removed from the room (via refreshing the page) there is no value, it just returns undefined. 

When should I use `:id`, `:string`, etc, and what are all the options?

Thanks in advance

**Comment by endel** [comment]
Hey @gregmax17, sorry, I'm a bit busy lately because I'm moving abroad, I'll write some more documentation as soon I get back to normal schedule :) 

> According to your example, the entities property for your state is assumed to be an array, correct?  In that example, `entities` is assumed to be a dictionary, like:

```
{
  entities: {
    'playerid1': { x: 0, y: 0 },
    'playerid2': { x: 0, y: 0 },
    'playerid3': { x: 0, y: 0 },
    // ...
  }
}
```

> From my experience when the user is removed from the room (via refreshing the page) there is no value, it just returns undefined.

That's correct. When a `remove` operation is performed, only the `path` of the variable that has been removed will be available.

> When should I use `:id`, `:string`, etc, and what are all the options?

Usually, you can just use `:your_own_identifier` - to be populated in the `path` whenever the callback is called. (`change.path.your_own_identifier`).

You can use `:id`, `:string`, `:number`, `:axis` to prevent path clashes. 

**For example:**
```
{
   entities: {
      "player1id": { 
        name: "Greg",
        x: 10,
        y: 10
      }
   }
}
```

Let's say the path `entities/playerid1/name` has been updated from `"Greg"` to `"gregmax17"`. If listen for changes using the `:axis` placeholder, the callback will be triggered only for changes on `x` and `y`.

You can see all the built-in placeholders here: https://github.com/endel/delta-listener/#built-in-placeholders

Cheers!

**Comment by endel** [comment]
I started writing about this in the wiki: https://github.com/gamestdio/colyseus/wiki/Patch-handling

**Comment by oyed** [comment]
I'm going to assume any required data to explain state synchronization is explained [here](https://docs.colyseus.io/client-state-synchronization/), otherwise, feel free to submit a PR [here](https://github.com/colyseus/docs/edit/master/docs/client-state-synchronization.md).
