### ISSUE TITLE
Allow to specify the protocol (SSL)

### ISSUE THREAD

**Issue by greaterweb** [colyseus/colyseus.js#68]
The `createMatchMakeRequest` method currently only supports requests with the [`http` protocol](https://github.com/colyseus/colyseus.js/blob/master/src/Client.ts#L83), it would be nice to have support for `https`.

I think the constructor could be modified to accept an optional second parameter to either explicitly set the protocol for http requests or it could be a flag to indicate that `https` is available.

```typescript
// explicitly set the protocol
enum SupportedProtocols {
  HTTP = 'http',
  HTTPS = 'https',
}
const client = new Colyseus.Client('ws://my-awesome.game', SupportedProtocols.HTTPS);

// or have a flag to use https
const USE_HTTPS = true;
const client = new Colyseus.Client('ws://my-awesome.game', USE_HTTPS);
```
As the parameter could be optional/have defaults this could viewed as a backward compatible enhancement.

I don't do have much game development experience but have been enjoying using this library, thanks for sharing it! I'd be happy to provide a PR for this feature if you have a preference to how you'd like to see this implemented.

Keep up the great work!

**Comment by endel** [comment]
Hi @greaterweb, thanks for the kind words.

If you use `wss://` instead of `ws://` it works though :)

I agree that the `Client` could have some options to "toggle" this automatically, as we currently do a hacky thing to perform the http(s) requests here: https://github.com/colyseus/colyseus.js/blob/master/src/Client.ts#L83

**Comment by greaterweb** [comment]
Thank you, @endel! That solution worked :)

**Comment by bcdbuddy** [comment]
nice solution by the way. I am closing https://github.com/colyseus/colyseus.js/issues/77

Thank you :+1:

**Comment by endel** [comment]
Related: https://github.com/colyseus/colyseus-unity3d/issues/120

**Comment by ttcong194** [comment]
@endel Currently, I use colyseus.js on cocos creator. My sever use https and wss. I saw Connection.ts of Client.ts extend from WebSocket.Everything is right  but as I built my project to android. I encountered error because websocket on native android of cocos not support ssl. 
There is one solution that add cacert.pem to Websocket like that
```javascript
let ws = new WebSocket( url, [], cc.url.raw("resources/cacert.pem") );
```
I saw WebSocketClient in package @gamestdio extend WebSocket. But I dont know how to insert cacert.pem to Connection of Client?

**Comment by luckybk93** [comment]
@ttcong194 file .pem bác tạo như nào vậy? Hay lấy file pem cấu hình https ở server?
E làm theo bác mà vẫn ko chạy :(

**Comment by ttcong194** [comment]
@luckybk93 Không biết bạn dùng client là gì bạn. Client mình là cocos creator. Trong  example của nó có file cacert.pem luôn bạn ah.
[https://github.com/cocos-creator/example-cases/blob/v2.4.3/assets/cases/05_scripting/10_network/cacert.pem](url)

**Comment by luckybk93** [comment]
For Cocos Creator
The solution in here:
https://github.com/cocos-creator/cocos2d-x-lite/issues/1722
Download file pem
https://curl.haxx.se/docs/caextract.html
Config file pem in here:
https://github.com/id-ilych/cc-web-socket-issue

**Comment by luckybk93** [comment]
Oke bác. M cũng cocos creator. Mới đầu cứ tưởng lấy file pem cấu hình ở
trên server.  Mãi đếch chạy.
Thanks bác nha

Vào 23:00 Th 5, 31 thg 12 2020 Tran Cong <notifications@github.com> đã viết:

**Comment by endel** [comment]
On version 0.15, this can be achieved like this:

```typescript
import { Client } from "colyseus.js";

const client = new Client({
  hostname: "us1.game.io", 
  secure: true,
  port: 1234, // optional
});
