### ISSUE TITLE
Why token is  generated on client side at time of auth?

### ISSUE THREAD

**Issue by chhaunkar96** [colyseus/colyseus.js#69]
We can see in the following request that token is going from the client-side with login details. why the token is generated on the client-side?? Can anyone explain it ?? It's confusing.

`await client.auth.login();`

![81102263-02b5f180-8f2d-11ea-8cc3-c84bd7610169](https://user-images.githubusercontent.com/29665934/81346538-12be0480-90d8-11ea-8364-08e4e552ada3.png)

**Comment by endel** [comment]
Hi @chhaunkar96, this is part of [@colyseus/social](https://github.com/colyseus/colyseus-social). 

The token is generated in the server. Maybe you had another token from the previous login, that's why you can see the token there as well. `@colyseus/social` haven't been maintained and improved since a few months - you can use it as inspiration for your own authentication methods, or fork and modify it for your needs
